// Auto-generated by scripts/balance.py — do not edit manually
import type { ItemType } from './types.ts';

export const INITIAL_COINS = 0;
export const INITIAL_SPARKLES = 0;
export const DEFAULT_UNLOCKED_EMOJIS: number[] = [0];

export const EMOJI_COIN_REWARDS: number[] = [1, 1, 2, 3, 4, 6, 9, 13, 19, 28, 41, 59, 86];

export const EMOJI_UNLOCK_COSTS: number[] = [0, 5, 8, 14, 24, 41, 70, 120, 205, 348, 592, 1007, 1713];

export const ITEM_COIN_COSTS: Record<ItemType, number> = {
  plant: 15,
  chair: 15,
  bedside_table: 23,
  coffee_table: 23,
  lamp: 23,
  table: 36,
  vase: 36,
  book: 36,
  drawer: 55,
  floor_lamp: 55,
  laptop: 55,
  mirror: 86,
  mirror_ornament: 86,
  boombox: 86,
  library: 134,
  tv: 134,
  wardrobe: 134,
  bed: 134,
};

export const ITEM_SPARKLE_REWARDS: Record<ItemType, number> = {
  plant: 3,
  chair: 3,
  bedside_table: 4,
  coffee_table: 4,
  lamp: 4,
  table: 6,
  vase: 6,
  book: 6,
  drawer: 10,
  floor_lamp: 10,
  laptop: 10,
  mirror: 15,
  mirror_ornament: 15,
  boombox: 15,
  library: 22,
  tv: 22,
  wardrobe: 22,
  bed: 22,
};
