// Auto-generated by scripts/balance.py — do not edit manually
import type { ItemType } from './types.ts';

export const INITIAL_COINS = 0;
export const INITIAL_SPARKLES = 0;
export const DEFAULT_UNLOCKED_EMOJIS: number[] = [0];

export const EMOJI_COIN_REWARDS: number[] = [1, 2, 3, 4, 6, 10, 16, 26, 42, 68, 109, 175, 281];

export const EMOJI_UNLOCK_COSTS: number[] = [0, 10, 18, 32, 58, 104, 188, 340, 612, 1101, 1983, 3570, 6426];

export const ITEM_COIN_COSTS: Record<ItemType, number> = {
  plant: 25,
  chair: 25,
  bedside_table: 43,
  coffee_table: 43,
  lamp: 43,
  table: 76,
  vase: 76,
  book: 76,
  drawer: 133,
  floor_lamp: 133,
  laptop: 133,
  mirror: 234,
  mirror_ornament: 234,
  boombox: 234,
  library: 410,
  tv: 410,
  wardrobe: 410,
  bed: 410,
};

export const ITEM_SPARKLE_REWARDS: Record<ItemType, number> = {
  plant: 2,
  chair: 2,
  bedside_table: 3,
  coffee_table: 3,
  lamp: 3,
  table: 5,
  vase: 5,
  book: 5,
  drawer: 8,
  floor_lamp: 8,
  laptop: 8,
  mirror: 13,
  mirror_ornament: 13,
  boombox: 13,
  library: 20,
  tv: 20,
  wardrobe: 20,
  bed: 20,
};

export const ITEM_MAX_PLACEMENTS: Record<ItemType, number> = {
  plant: 3,
  chair: 3,
  bedside_table: 3,
  coffee_table: 3,
  lamp: 3,
  table: 2,
  vase: 3,
  book: 3,
  drawer: 2,
  floor_lamp: 2,
  laptop: 3,
  mirror: 2,
  mirror_ornament: 2,
  boombox: 2,
  library: 2,
  tv: 2,
  wardrobe: 2,
  bed: 2,
};
