// Auto-generated by scripts/balance.py — do not edit manually
import type { ItemType } from './types.ts';

export const INITIAL_COINS = 0;
export const INITIAL_SPARKLES = 0;
export const DEFAULT_UNLOCKED_EMOJIS: number[] = [0];

export const EMOJI_COIN_REWARDS: number[] = [1, 2, 3, 4, 6, 10, 16, 26, 42, 68, 109, 175, 281];

export const EMOJI_UNLOCK_COSTS: number[] = [0, 7, 12, 21, 37, 65, 114, 201, 351, 615, 1077, 1885, 3300];

export const ITEM_COIN_COSTS: Record<ItemType, number> = {
  plant: 21,
  chair: 21,
  bedside_table: 36,
  coffee_table: 36,
  lamp: 36,
  table: 62,
  vase: 62,
  book: 62,
  drawer: 108,
  floor_lamp: 108,
  laptop: 108,
  mirror: 188,
  mirror_ornament: 188,
  boombox: 188,
  library: 325,
  tv: 325,
  wardrobe: 325,
  bed: 325,
};

export const ITEM_SPARKLE_REWARDS: Record<ItemType, number> = {
  plant: 3,
  chair: 3,
  bedside_table: 4,
  coffee_table: 4,
  lamp: 4,
  table: 7,
  vase: 7,
  book: 7,
  drawer: 12,
  floor_lamp: 12,
  laptop: 12,
  mirror: 19,
  mirror_ornament: 19,
  boombox: 19,
  library: 31,
  tv: 31,
  wardrobe: 31,
  bed: 31,
};

export const ITEM_MAX_PLACEMENTS: Record<ItemType, number> = {
  plant: 6,
  chair: 6,
  bedside_table: 6,
  coffee_table: 6,
  lamp: 6,
  table: 4,
  vase: 6,
  book: 6,
  drawer: 4,
  floor_lamp: 4,
  laptop: 6,
  mirror: 4,
  mirror_ornament: 4,
  boombox: 4,
  library: 4,
  tv: 4,
  wardrobe: 4,
  bed: 4,
};
