import type { ItemType, ItemDefinition } from './types.ts';

export const ITEM_DEFINITIONS: Record<ItemType, ItemDefinition> = {
  table: {
    label: 'tavolo',
    type: 'table',
    category: 'floor',
    size: 1,
    connectable: true,
    connectableDirections: 'all',
    rotationStrategy: 'faceAwayFromWall',
    interactable: true,
    surfaceHeight: 1.0,
    variants: 4,
  },
  chair: {
    label: 'sedia',
    type: 'chair',
    category: 'floor',
    size: 1,
    connectable: true,
    rotationStrategy: 'faceInteractable',
    variants: 8,
  },
  plant: {
    label: 'pianta',
    type: 'plant',
    category: 'floor',
    size: 1,
    rotationStrategy: 'faceAwayFromWall',
    variants: 4,
  },
  library: {
    label: 'libreria',
    type: 'library',
    category: 'floor',
    size: 1,
    connectable: true,
    rotationStrategy: 'faceAwayFromWall',
    variants: 4,
    previewAdjustCamera: 1.8,
  },
  floor_lamp: {
    label: 'piantana',
    type: 'floor_lamp',
    category: 'floor',
    size: 1,
    rotationStrategy: 'faceAwayFromWall',
    variants: 4,
    previewAdjustCamera: 1.15,
  },
  bed: {
    label: 'letto',
    type: 'bed',
    category: 'floor',
    size: 2,
    stackable: true,
    connectable: true,
    rotationStrategy: 'manual',
    variants: 4,
    previewAdjustCamera: 1.8,
  },
  laptop: {
    label: 'portatile',
    type: 'laptop',
    category: 'surface',
    size: 1,
    rotationStrategy: 'faceChair',
    facingType: 'chair',
    interactable: true,
    variants: 4,
    previewAdjustCamera: 0.8,
  },
  tv: {
    type: 'tv',
    label: 'TV',
    category: 'surface',
    size: 1,
    connectable: true,
    rotationStrategy: 'faceChair',
    interactable: true,
    variants: 4,
  },
  vase: {
    label: 'vaso',
    type: 'vase',
    category: 'surface',
    size: 1,
    rotationStrategy: 'faceChair',
    variants: 4,
    previewAdjustCamera: 0.8,
  },
  book: {
    label: 'libro',
    type: 'book',
    category: 'surface',
    size: 1,
    interactable: true,
    rotationStrategy: 'faceChair',
    variants: 4,
    previewAdjustCamera: 0.8,
  },
  lamp: {
    label: 'lampada',
    type: 'lamp',
    category: 'surface',
    size: 1,
    rotationStrategy: 'faceChair',
    variants: 4,
    previewAdjustCamera: 0.8,
  },
  drawer: {
    label: 'comò',
    type: 'drawer',
    category: 'floor',
    size: 1,
    connectable: true,
    rotationStrategy: 'faceAwayFromWall',
    surfaceHeight: 0.8,
    variants: 4,
  },
  bedside_table: {
    label: 'comodino',
    type: 'bedside_table',
    category: 'floor',
    size: 1,
    rotationStrategy: 'faceAwayFromWall',
    surfaceHeight: 0.5,
    variants: 4,
    previewAdjustCamera: 0.9,
  },
  wardrobe: {
    label: 'armadio',
    type: 'wardrobe',
    category: 'floor',
    size: 1,
    connectable: true,
    rotationStrategy: 'faceAwayFromWall',
    variants: 4,
    previewAdjustCamera: 1.6,
  },
  coffee_table: {
    label: 'tavolino',
    type: 'coffee_table',
    category: 'floor',
    size: 1,
    connectable: true,
    rotationStrategy: 'faceAwayFromWall',
    interactable: true,
    surfaceHeight: 0.46,
    variants: 4,
  },
  mirror: {
    label: 'specchio',
    type: 'mirror',
    category: 'floor',
    size: 1,
    connectable: true,
    rotationStrategy: 'faceAwayFromWall',
    variants: 4,
    previewAdjustCamera: 1.3,
  },
  mirror_ornament: {
    label: 'specchietto',
    type: 'mirror_ornament',
    category: 'surface',
    size: 1,
    interactable: true,
    rotationStrategy: 'faceChair',
    variants: 4,
    previewAdjustCamera: 0.8,
  },
  boombox: {
    label: 'radio',
    type: 'boombox',
    category: 'surface',
    size: 1,
    interactable: true,
    rotationStrategy: 'faceAwayFromWall',
    variants: 4,
    previewAdjustCamera: 0.8,
  },
};
